"""update workorders 

Revision ID: 21e89587bb26
Revises: db6a47a1f73a
Create Date: 2023-08-26 20:50:28.090537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e89587bb26'
down_revision = 'db6a47a1f73a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
