"""change uuid

Revision ID: ab79b790ec0a
Revises: 56f0c5d4b906
Create Date: 2023-08-24 20:06:03.749723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab79b790ec0a'
down_revision = '56f0c5d4b906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customers', ['id'])
    op.create_unique_constraint(None, 'work_orders', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    # ### end Alembic commands ###
