"""default false

Revision ID: db6a47a1f73a
Revises: ab79b790ec0a
Create Date: 2023-08-24 20:26:49.855764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6a47a1f73a'
down_revision = 'ab79b790ec0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
